site_name: CMIP7 experiment description scratch
site_description: Scratch repository for testing out building of CMIP7 experiment definition docs.
site_url: https://cmip7-experiment-description-scratch.readthedocs.io
edit_uri: blob/main/docs/

repo_name: climate-resource/cmip7-experiment-description-scratch
repo_url: https://github.com/climate-resource/cmip7-experiment-description-scratch

theme: readthedocs

plugins:
  # Make the navigation easier to handle/auto-generate if we wish
  # https://oprypin.github.io/mkdocs-literate-nav/
  - literate-nav:
      nav_file: NAVIGATION.md
