site_name: CMIP7 experiment description scratch
site_description: Scratch repository for testing out building of CMIP7 experiment definition docs.
site_url: https://cmip7-experiment-description-scratch.readthedocs.io
edit_uri: blob/main/docs/

repo_name: climate-resource/cmip7-experiment-description-scratch
repo_url: https://github.com/climate-resource/cmip7-experiment-description-scratch

theme: readthedocs

nav:
  - Home: index.md
  - Experiment overviews:
    # TODO: auto-generate this using literate-nav
    - piControl: picontrol.md
    - abrupt-4xCO2: abrupt-4xCO2.md
    - abrupt-2xCO2: abrupt-2xCO2.md
    - historical: historical.md
